# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def rx_swift
    pod 'RxSwift'
end

def rx_cocoa
    pod 'RxCocoa'
end

def rx_swift_ext
    pod 'RxSwiftExt'
end

def rx_dataSource
    pod 'RxDataSources'
end
    
def test_pods
    pod 'RxTest'
    pod 'RxBlocking'
    pod 'Nimble'
end

target 'Domain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  rx_swift
  # Pods for Domain

  target 'DomainTests' do
    inherit! :search_paths
    test_pods
  end

end

target 'Frames-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  rx_swift
  rx_cocoa
  rx_swift_ext
  rx_dataSource
  
  # Pods for Frames-App
    pod 'RxSwift'

  target 'Frames-AppTests' do
    inherit! :search_paths
    test_pods
  end

  target 'Frames-AppUITests' do
    inherit! :search_paths
    test_pods
  end

end

target 'NetworkPlatform' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  rx_swift
  rx_cocoa
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'AWSAppSync', '~> 2.6.24'

  target 'NetworkPlatformTests' do
    inherit! :search_paths
    test_pods
  end

end
